apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base
- httproute.yaml
- externalsecret.yaml
- database.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/portfolio
  newTag: v1.0.2
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations/resource.opentelemetry.io~1deployment.environment.name
      value: prod
  target:
    kind: Deployment
    name: portfolio
