apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
- httproute.yaml
- externalsecret.yaml
- database.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/portfolio
  newTag: c227f1bc3060f9129e25a936c3f0f27917f1fd1e
