apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
- httproute.yaml
- externalsecret.yaml
- database.yaml
images:
- name: ghcr.io/zing-rsa/portfolio
  newTag: e1265fa893b8a98fb5d0848023162d08e06c688d
