apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
- httproute.yaml
- externalsecret.yaml
- database.yaml
images:
- name: ghcr.io/zing-rsa/portfolio
  newTag: 2309472dd25e4510f630113266f6d03b8de4a658
