apiVersion: apps/v1
kind: Deployment
metadata: { name: portfolio, labels: { app: portfolio } }
spec:
  replicas: 1
  selector: { matchLabels: { app: portfolio } }
  template:
    metadata: { labels: { app: portfolio } }
    spec:
      imagePullSecrets: [{ name: ghcr }]
      containers:
        - name: portfolio
          image: ghcr.io/zing-rsa/portfolio
          ports: [{ containerPort: 3000 }]
          envFrom:
            - secretRef: { name: portfolio-app }
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { memory: 384Mi }