name: ci
on:
  pull_request:
  push: { branches: [main] }
  release: { types: [published] }
jobs:
  build:
    permissions: { contents: read, packages: write }
    uses: zing-rsa/lab/.github/workflows/build.yml@main
  deploy-dev:
    if: github.event_name == 'push'
    needs: build
    permissions: { contents: write }
    uses: zing-rsa/lab/.github/workflows/deploy.yml@main
    with:
      env: dev
      tag: ${{ github.sha }}
  deploy-prod:
    if: github.event_name == 'release'
    needs: build
    permissions: { contents: write }
    uses: zing-rsa/lab/.github/workflows/deploy.yml@main
    with:
      env: prod
      tag: ${{ github.event.release.tag_name }}
